import Head from "next/head"
import styles from "../styles/Home.module.css"
import Navbar from "../components/navbar"

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Emily Herndon&apos;s Portfolio</title>
				<meta
					name="Emily Herndon's Portfolio"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<nav>
				<Navbar />
			</nav>
			<main></main>
		</div>
	)
}
